# values-qa.yaml
namespace: qa
replicaCount: 2

image:
  repository: 132514887880.dkr.ecr.ap-south-1.amazonaws.com/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# ✅ Add this section to let Kubernetes pull from ECR
imagePullSecrets:
  - name: ecr-secret

env:
  APP_ENV: qa
  LOG_LEVEL: info

